# Checkpoint Four: Data Manipulation

My dataset: https://www.kaggle.com/datasets/ngshiheng/michelin-guide-restaurants-2021

In [1]:
# Importing Pandas to clean data.
# Importing SQLite3 for easier querying of data.
# Importing Matplotlib, Matplotlib.pyplot, Seaborn, and Numpy for visualiztion.

import pandas as pd
import sqlite3 as sl
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Reading data.
df1 = pd.read_csv('Michelin Guide Data_cleaned.csv')
df1

,Name,LocationCountry,Latitude,Longitude,Cuisine,Currency,Priciness,HasPhone,HasWebsite,FacilitiesAndServices,Award
0,Quince,USA,37.797505,-122.403261,"Contemporary, Californian",$,4.0,True,True,"Air conditioning,American Express credit card,...",3 MICHELIN Stars
1,Atelier Crenn,USA,37.798350,-122.435860,"Contemporary, French",$,4.0,True,True,"Air conditioning,Credit card / Debit card acce...",3 MICHELIN Stars
2,Addison,USA,32.941297,-117.198891,"Contemporary, Californian",$,4.0,True,True,"Air conditioning,American Express credit card,...",3 MICHELIN Stars
3,Manresa,USA,37.227610,-121.980710,"Contemporary, Californian",$,4.0,True,True,"Air conditioning,Credit card / Debit card acce...",3 MICHELIN Stars
4,Benu,USA,37.785376,-122.399060,"Asian, Contemporary",$,4.0,True,True,"Air conditioning,Credit card / Debit card acce...",3 MICHELIN Stars
...,...,...,...,...,...,...,...,...,...,...,...
6790,Szóstka,Poland,52.235803,21.012698,"Polish, Modern Cuisine",€,2.0,True,True,"Air conditioning,American Express credit card,...",Bib Gourmand
6791,Fiorentina,Poland,50.055898,19.938179,"Creative, Polish",€,2.0,True,True,"Air conditioning,American Express credit card,...",Bib Gourmand
6792,Zazie,Poland,50.051240,19.946949,French,€,1.0,True,True,"Air conditioning,Booking essential - dinner,Cr...",Bib Gourmand
6793,Butchery & Wine,Poland,52.228581,21.015495,"Meats and Grills, Traditional Cuisine",€,2.0,True,True,"American Express credit card,Booking essential...",Bib Gourmand
6794,alewino,Poland,52.225201,21.022057,"Polish, Traditional Cuisine",€,2.0,True,True,"Air conditioning,American Express credit card,...",Bib Gourmand

In [2]:
# Separating out multiple cuisine values for a count.
df1[['Cuisine1','Cuisine2']] = df1['Cuisine'].str.split(', ',expand=True)
df1

,Name,LocationCountry,Latitude,Longitude,Cuisine,Currency,Priciness,HasPhone,HasWebsite,FacilitiesAndServices,Award,Cuisine1,Cuisine2
0,Quince,USA,37.797505,-122.403261,"Contemporary, Californian",$,4.0,True,True,"Air conditioning,American Express credit card,...",3 MICHELIN Stars,Contemporary,Californian
1,Atelier Crenn,USA,37.798350,-122.435860,"Contemporary, French",$,4.0,True,True,"Air conditioning,Credit card / Debit card acce...",3 MICHELIN Stars,Contemporary,French
2,Addison,USA,32.941297,-117.198891,"Contemporary, Californian",$,4.0,True,True,"Air conditioning,American Express credit card,...",3 MICHELIN Stars,Contemporary,Californian
3,Manresa,USA,37.227610,-121.980710,"Contemporary, Californian",$,4.0,True,True,"Air conditioning,Credit card / Debit card acce...",3 MICHELIN Stars,Contemporary,Californian
4,Benu,USA,37.785376,-122.399060,"Asian, Contemporary",$,4.0,True,True,"Air conditioning,Credit card / Debit card acce...",3 MICHELIN Stars,Asian,Contemporary
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6790,Szóstka,Poland,52.235803,21.012698,"Polish, Modern Cuisine",€,2.0,True,True,"Air conditioning,American Express credit card,...",Bib Gourmand,Polish,Modern Cuisine
6791,Fiorentina,Poland,50.055898,19.938179,"Creative, Polish",€,2.0,True,True,"Air conditioning,American Express credit card,...",Bib Gourmand,Creative,Polish
6792,Zazie,Poland,50.051240,19.946949,French,€,1.0,True,True,"Air conditioning,Booking essential - dinner,Cr...",Bib Gourmand,French,None
6793,Butchery & Wine,Poland,52.228581,21.015495,"Meats and Grills, Traditional Cuisine",€,2.0,True,True,"American Express credit card,Booking essential...",Bib Gourmand,Meats and Grills,Traditional Cuisine
6794,alewino,Poland,52.225201,21.022057,"Polish, Traditional Cuisine",€,2.0,True,True,"Air conditioning,American Express credit card,...",Bib Gourmand,Polish,Traditional Cuisine

In [17]:
df1_1 = df1[['Cuisine1']]
df1_1.rename(columns={'Cuisine1': 'CuisineSeparated'},inplace=True)
df1_2 = df1[['Cuisine2']]
df1_2.rename(columns={'Cuisine2': 'CuisineSeparated'},inplace=True)
df_cuisines = pd.concat([df1_1, df1_2], ignore_index=True)
df_cuisines_count = df_cuisines.value_counts()
df_cuisines_count

C:\Users\JChou\AppData\Local\Temp\ipykernel_22060\1611767178.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_1.rename(columns={'Cuisine1': 'CuisineSeparated'},inplace=True)
C:\Users\JChou\AppData\Local\Temp\ipykernel_22060\1611767178.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_2.rename(columns={'Cuisine2': 'CuisineSeparated'},inplace=True)

CuisineSeparated
Modern Cuisine         1501
Creative                804
Contemporary            408
Traditional Cuisine     389
Japanese                364
                       ...
Emirati Cuisine           1
Sujebi                    1
Pork Specialities         1
Dongbei                   1
Afghan                    1
Length: 243, dtype: int64

In [18]:
# Reading info into a separate csv file:
df1.to_csv('Michelin Guide Data_Separated_Cuisines.csv', index=False)
df_cuisines_count.to_csv('Michelin Guide Data_Cuisine_Count.csv')